### PR TITLE
New Icons thanks to OpenClipArt & Inkscape

### PR DESCRIPTION
**Pull request by Adrianzo**
So, I had to drop the idea of the fist sprouting from the onion 'cause it didn't look well in a tiny icon. But at least this is something!

### CODE REVIEW

**Comment by reezer** [comment]
Thank you for the logo. However, I am not sure if inactive should be yellow on a green, yellow, red scale. Inactive describes the situation that everything is working as intended. It is the default state. Yellow seems a lot like a warning color (especially on this Red/Green/Yellow). So I think we should have green as a default and another color as active - something that currently barely happens.

I'd love to hear your opinion. If we'd take green as inactive would you make the active one yellow or another color, or maybe even a modification to the logo itself?

**Comment by Adrianzo** [comment]
active could be something like a rainbow onion, representing something happy and diversity itself (as a value). IMHO we are defending diversity of views while fighting censorship.

I'd like to try something in these lines of thinking, in the next few days.

PS. I used dark yellow on purpose, trying to avoid the issue that you mention. I thought it would look like a normal onion... but that would have been orange. Maybe that's another option. Anyway, I like the rainbow idea a lot more!

**Comment by reezer** [comment]
I like the rainbow idea. Feel free to send a pull request. :)

**Comment by reezer** [comment]
Closing this now. Please just create a new pull request for the new icon. :)

**Pull request closed without merging**
